"""Asynchronous progressive observer and summarizer for target terminal agents."""
import logging
import os
import re
import sys
import time
from dataclasses import dataclass
from typing import Optional, List, Dict, Any, Tuple, Callable
from .session_detector import TerminalSession
from .buffer_capture import BufferCapture

logger = logging.getLogger(__name__)

C_PURPLE = "\033[38;5;129m"
C_PINK = "\033[38;5;205m"
C_LAVENDER = "\033[38;5;183m"
C_LILAC = "\033[38;5;147m"
C_MID = "\033[38;5;99m"
C_GRAY = "\033[38;5;244m"
RESET = "\033[0m"
DIM = "\033[2m"
BOLD = "\033[1m"


@dataclass
class ObservationResult:
    """The outcome of observing the target agent's response."""
    status: str                       # "completed" | "in_progress" | "interrupted" | "error"
    full_output: str                  # full new text generated by the agent
    summary: Optional[str] = None     # structured summary if still in progress
    tools_executed: List[str] = None  # extracted tools/commands
    current_activity: Optional[str] = None
    stage: int = 1


class AgentObserver:
    """Monitors target session buffer across exponential wait stages until completion."""

    IDLE_PROMPT_PATTERNS = [
        re.compile(r"(?:[❯>▶]|>>>|\?)\s*$"),
        re.compile(r"\[.*@.*\][#$]\s*$"),
        re.compile(r"\(agent\)\s*>\s*$"),
        re.compile(r"msg=interrupt", re.I),
        re.compile(r"ctrl\+c to cancel", re.I),
        re.compile(r"Total time:", re.I),
        re.compile(r"Finished in\b", re.I),
    ]

    TOOL_EXEC_PATTERNS = [
        re.compile(r"(?:Ran|Running|Executing|Command|\$)\s*[:·]?\s*(.+)", re.I),
        re.compile(r"(?:Read|Edited|Wrote|Created|Deleted|Patching)\s+([A-Za-z0-9_\-./\\]+)", re.I),
        re.compile(r"(\b[a-z_]+_tool\b|\btool_use\b|\bcall:\s*[a-z_]+)", re.I),
        re.compile(r"(?:pytest|npm|cargo|go|python|node|git|uv|pip)\s+[^\n]+"),
    ]

    # Progressive exponential wait stages: 10s (initial check), 60s (1m), 120s (2m), 240s (4m), 300s (5m)
    WAIT_STAGES = [10.0, 60.0, 120.0, 240.0, 300.0]

    def __init__(self, buffer_capture: Optional[BufferCapture] = None):
        self.buffer_capture = buffer_capture or BufferCapture()

    def observe_session(
        self,
        session: TerminalSession,
        initial_buffer: str,
        ai_client: Any,
        on_interim_summary: Optional[Callable[[ObservationResult], None]] = None,
        max_stages: int = 5,
    ) -> ObservationResult:
        """
        Progressive exponential observation loop:
        1. Waits through stages (10s -> 1m -> 2m -> 4m -> 5m).
        2. If agent completes at any point, returns immediately with full output.
        3. At the end of each stage, produces a structured progress summary and notifies via callback.
        4. Continues until the agent completes or user interrupts with Ctrl+C.
        """
        prev_output = ""
        current_new_output = ""
        overall_start = time.time()

        # Initial breath for keystrokes to settle
        time.sleep(1.0)

        # Check for transcript log if conversation ID exists
        conv_id = getattr(session, "extra", {}).get("conv_id")
        transcript_path = None
        initial_transcript_lines = 0
        if conv_id:
            tpath = os.path.expanduser(f"~/.gemini/antigravity-cli/brain/{conv_id}/.system_generated/logs/transcript.jsonl")
            if os.path.exists(tpath):
                transcript_path = tpath
                try:
                    with open(transcript_path, "r", encoding="utf-8", errors="replace") as f:
                        initial_transcript_lines = len(f.readlines())
                except Exception:
                    pass

        for stage_idx, stage_duration in enumerate(self.WAIT_STAGES[:max_stages], start=1):
            stage_start = time.time()
            last_change_time = stage_start

            try:
                while (time.time() - stage_start) < stage_duration:
                    elapsed = time.time() - overall_start
                    stage_elapsed = time.time() - stage_start

                    # Update status bar via HUD if available
                    from rays_core import rays_ui
                    rays_ui.hud_set_status("Observing", f"{session.agent_name} · {int(elapsed)}s · executing...")

                    # 1. Check direct transcript turn completion (instant & 100% accurate)
                    if transcript_path and os.path.exists(transcript_path):
                        try:
                            with open(transcript_path, "r", encoding="utf-8", errors="replace") as f:
                                lines = f.readlines()
                            if len(lines) > initial_transcript_lines:
                                last_entry = json.loads(lines[-1])
                                if last_entry.get("source") == "MODEL" and last_entry.get("content"):
                                    return ObservationResult(
                                        status="completed",
                                        full_output=last_entry.get("content").strip(),
                                        summary=None,
                                        stage=stage_idx
                                    )
                        except Exception:
                            pass

                    # Poll buffer
                    current_buf = self.buffer_capture.capture_recent_lines(session, num_lines=150)
                    current_new_output = self.buffer_capture.compute_new_output(initial_buffer, current_buf)

                    if current_new_output != prev_output:
                        prev_output = current_new_output
                        last_change_time = time.time()

                    # Check completion:
                    # 1. If buffer contains completed Assistant turn response
                    if "Assistant:" in current_new_output and len(current_new_output.strip()) > 40:
                        clean_output = self._clean_final_output(current_new_output)
                        return ObservationResult(
                            status="completed",
                            full_output=clean_output,
                            summary=None,
                            stage=stage_idx
                        )

                    # 2. Output stable for >= 2.5s and ends with prompt character
                    time_since_change = time.time() - last_change_time
                    if time_since_change >= 2.5 and current_new_output.strip():
                        last_line = current_new_output.strip().splitlines()[-1]
                        if any(p.search(last_line) for p in self.IDLE_PROMPT_PATTERNS):
                            clean_output = self._clean_final_output(current_new_output)
                            return ObservationResult(
                                status="completed",
                                full_output=clean_output,
                                summary=None,
                                stage=stage_idx
                            )

                    time.sleep(1.2)

                # Re-check once at stage boundary
                current_buf = self.buffer_capture.capture_recent_lines(session, num_lines=150)
                current_new_output = self.buffer_capture.compute_new_output(initial_buffer, current_buf)
                if current_new_output.strip():
                    if "Assistant:" in current_new_output and len(current_new_output.strip()) > 40:
                        clean_output = self._clean_final_output(current_new_output)
                        return ObservationResult(
                            status="completed",
                            full_output=clean_output,
                            summary=None,
                            stage=stage_idx
                        )
                    last_line = current_new_output.strip().splitlines()[-1]
                    if any(p.search(last_line) for p in self.IDLE_PROMPT_PATTERNS):
                        clean_output = self._clean_final_output(current_new_output)
                        return ObservationResult(
                            status="completed",
                            full_output=clean_output,
                            summary=None,
                            stage=stage_idx
                        )

                # Stage finished but agent is STILL WORKING:
                # Generate interim summary of what has been done and what it is doing
                tools_run, current_act = self._extract_activity_heuristics(current_new_output, session)
                stage_summary = self._generate_progress_summary(
                    session=session,
                    output_snippet=current_new_output,
                    tools_run=tools_run,
                    current_act=current_act,
                    ai_client=ai_client,
                    stage_idx=stage_idx
                )

                interim_res = ObservationResult(
                    status="in_progress",
                    full_output=current_new_output,
                    summary=stage_summary,
                    tools_executed=tools_run,
                    current_activity=current_act,
                    stage=stage_idx
                )

                # Invoke UI callback to render the interim progress box in RAYS theme
                if on_interim_summary:
                    on_interim_summary(interim_res)

            except KeyboardInterrupt:
                sys.stdout.write(f"\r{' ' * 75}\r")
                sys.stdout.flush()
                print(f"\n  {C_LILAC}⊙ Observation paused — {session.agent_name} continues running in `{session.session_id}`.{RESET}\n")
                return ObservationResult(
                    status="interrupted",
                    full_output=current_new_output,
                    summary="Observation paused by user.",
                    stage=stage_idx
                )

        # Reached end of max stages
        return ObservationResult(
            status="in_progress",
            full_output=current_new_output,
            summary=stage_summary,
            stage=len(self.WAIT_STAGES)
        )

    def _clean_final_output(self, raw_output: str) -> str:
        """Strip preceding prompt/turns and trailing interactive prompt characters from final output."""
        text = raw_output
        if "Assistant:" in text:
            # Extract only the last Assistant response block
            parts = text.split("Assistant:")
            text = parts[-1].strip()
        lines = text.splitlines()
        while lines and any(p.search(lines[-1].strip()) for p in self.IDLE_PROMPT_PATTERNS):
            lines.pop()
        return "\n".join(lines).strip()

    def _extract_activity_heuristics(self, output: str, session: TerminalSession) -> Tuple[List[str], str]:
        """Extract executed tools, commands, and current activity heuristically from output and cwd."""
        tools_found = []
        lines = output.splitlines() if output else []
        for line in lines:
            line_str = line.strip()
            for pat in self.TOOL_EXEC_PATTERNS:
                m = pat.search(line_str)
                if m:
                    tools_found.append(line_str[:80])
                    break

        unique_tools = []
        for t in tools_found:
            if t not in unique_tools:
                unique_tools.append(t)

        # If terminal scrollback is brief, check if git status or files changed in session.cwd
        if not unique_tools and session.cwd and os.path.isdir(session.cwd):
            try:
                import subprocess
                gs = subprocess.run(["git", "status", "--short"], cwd=session.cwd, capture_output=True, text=True, timeout=1.0)
                if gs.returncode == 0 and gs.stdout.strip():
                    changed = [l.strip() for l in gs.stdout.strip().splitlines()[:4]]
                    unique_tools.extend([f"Modified: {c}" for c in changed])
            except Exception:
                pass

        current_activity = lines[-1].strip() if lines else f"{session.agent_name} is processing prompt in {session.cwd}..."
        return unique_tools[:8], current_activity

    def _generate_progress_summary(
        self,
        session: TerminalSession,
        output_snippet: str,
        tools_run: List[str],
        current_act: str,
        ai_client: Any,
        stage_idx: int = 1
    ) -> str:
        """Synthesize an interim progress summary using the LLM (or heuristic fallback)."""
        prompt = (
            f"You are summarizing in-progress execution of an AI agent ({session.agent_name} in {session.cwd}).\n"
            f"The agent has received a prompt and is currently performing actions.\n"
            f"Here is the recent terminal output produced so far:\n"
            f"```\n{output_snippet[-1500:]}\n```\n\n"
            f"Provide a concise 2-3 bullet point summary:\n"
            f"1. What tools/files/commands have been executed so far.\n"
            f"2. What the agent is currently working on or waiting for.\n"
            f"Keep it clear, helpful, and brief."
        )

        try:
            if hasattr(ai_client, "generate_text") and output_snippet.strip():
                summary = ai_client.generate_text(prompt)
                if summary and summary.strip():
                    return summary.strip()
        except Exception:
            pass

        # Clean structured fallback
        bullets = [f"**Status**: Active ({session.agent_name} is executing task)"]
        if tools_run:
            bullets.append("**Actions / tools executed so far**:")
            for t in tools_run[:5]:
                bullets.append(f"  • `{t}`")
        else:
            bullets.append(f"• **Session**: `{session.session_id}` in `{session.cwd}`")
            bullets.append(f"• **Activity**: {current_act}")
        return "\n".join(bullets)
